Small fix in Markdown format
uploadcare/angular-uploadcare pull request #21
Opened 2017-04-20 11:03 UTC by valery1707

2017-04-20 12:37 UTC, Zmoki requested changes

2017-04-20 12:37 UTC, Zmoki commented on README.md
> +### Usage
it's first level header, not third. keep just space.

2017-04-20 12:37 UTC, Zmoki commented on README.md
> +### Options
it's first level header, not third. keep just space.

2017-04-20 15:31 UTC, valery1707 commented
@Zmoki fixed

2017-04-27 11:17 UTC, Zmoki approved these changes

2017-04-27 11:17 UTC, Zmoki commented
@valery1707 thank you!

2017-04-28 12:20 UTC, valery1707 commented
@Zmoki will you merge this changes?

2017-04-28 13:14 UTC, Zmoki commented
@valery1707 sure. I waited for the tests to pass

2017-04-28 13:14 UTC, merged